import type { NFLPlayer } from "@jimmiesgame/shared";

/**
 * Curated snapshot of real active NFL players for local/dev/demo use, sized
 * so a full multi-team draft (solo mode default: 1 user + up to 10 bots,
 * 15-man rosters) never exhausts the pool. A production deployment replaces
 * this with a live sync from the configured StatsProvider (SportsDataIO /
 * Sleeper / nflverse); external IDs here are placeholders that a real
 * provider's IDs would populate.
 */
export const SEED_PLAYERS: Omit<NFLPlayer, "id">[] = [
  // Quarterbacks
  { name: "Patrick Mahomes", realNflTeam: "KC", position: "QB", externalId: "qb-mahomes", jerseyNumber: 15 },
  { name: "Josh Allen", realNflTeam: "BUF", position: "QB", externalId: "qb-allen", jerseyNumber: 17 },
  { name: "Lamar Jackson", realNflTeam: "BAL", position: "QB", externalId: "qb-ljackson", jerseyNumber: 8 },
  { name: "Jalen Hurts", realNflTeam: "PHI", position: "QB", externalId: "qb-hurts", jerseyNumber: 1 },
  { name: "Joe Burrow", realNflTeam: "CIN", position: "QB", externalId: "qb-burrow", jerseyNumber: 9 },
  { name: "Justin Herbert", realNflTeam: "LAC", position: "QB", externalId: "qb-herbert", jerseyNumber: 10 },
  { name: "C.J. Stroud", realNflTeam: "HOU", position: "QB", externalId: "qb-stroud", jerseyNumber: 7 },
  { name: "Jayden Daniels", realNflTeam: "WAS", position: "QB", externalId: "qb-daniels", jerseyNumber: 5 },
  { name: "Dak Prescott", realNflTeam: "DAL", position: "QB", externalId: "qb-prescott", jerseyNumber: 4 },
  { name: "Kyler Murray", realNflTeam: "ARI", position: "QB", externalId: "qb-murray", jerseyNumber: 1 },
  { name: "Brock Purdy", realNflTeam: "SF", position: "QB", externalId: "qb-purdy", jerseyNumber: 13 },
  { name: "Jared Goff", realNflTeam: "DET", position: "QB", externalId: "qb-goff", jerseyNumber: 16 },
  { name: "Jordan Love", realNflTeam: "GB", position: "QB", externalId: "qb-love", jerseyNumber: 10 },
  { name: "Baker Mayfield", realNflTeam: "TB", position: "QB", externalId: "qb-mayfield", jerseyNumber: 6 },
  { name: "Matthew Stafford", realNflTeam: "LAR", position: "QB", externalId: "qb-stafford", jerseyNumber: 9 },
  { name: "Trevor Lawrence", realNflTeam: "JAX", position: "QB", externalId: "qb-lawrence", jerseyNumber: 16 },
  { name: "Caleb Williams", realNflTeam: "CHI", position: "QB", externalId: "qb-cwilliams", jerseyNumber: 18 },
  { name: "Bo Nix", realNflTeam: "DEN", position: "QB", externalId: "qb-nix", jerseyNumber: 10 },
  { name: "Geno Smith", realNflTeam: "LV", position: "QB", externalId: "qb-gsmith", jerseyNumber: 7 },
  { name: "Sam Darnold", realNflTeam: "SEA", position: "QB", externalId: "qb-darnold", jerseyNumber: 14 },

  // Running Backs
  { name: "Christian McCaffrey", realNflTeam: "SF", position: "RB", externalId: "rb-cmc", jerseyNumber: 23 },
  { name: "Bijan Robinson", realNflTeam: "ATL", position: "RB", externalId: "rb-brobinson", jerseyNumber: 7 },
  { name: "Saquon Barkley", realNflTeam: "PHI", position: "RB", externalId: "rb-barkley", jerseyNumber: 26 },
  { name: "Jahmyr Gibbs", realNflTeam: "DET", position: "RB", externalId: "rb-gibbs", jerseyNumber: 26 },
  { name: "Derrick Henry", realNflTeam: "BAL", position: "RB", externalId: "rb-henry", jerseyNumber: 22 },
  { name: "Breece Hall", realNflTeam: "NYJ", position: "RB", externalId: "rb-hall", jerseyNumber: 20 },
  { name: "Jonathan Taylor", realNflTeam: "IND", position: "RB", externalId: "rb-jtaylor", jerseyNumber: 28 },
  { name: "De'Von Achane", realNflTeam: "MIA", position: "RB", externalId: "rb-achane", jerseyNumber: 28 },
  { name: "Kyren Williams", realNflTeam: "LAR", position: "RB", externalId: "rb-kwilliams", jerseyNumber: 23 },
  { name: "James Cook", realNflTeam: "BUF", position: "RB", externalId: "rb-cook", jerseyNumber: 4 },
  { name: "Josh Jacobs", realNflTeam: "GB", position: "RB", externalId: "rb-jacobs", jerseyNumber: 8 },
  { name: "Alvin Kamara", realNflTeam: "NO", position: "RB", externalId: "rb-kamara", jerseyNumber: 41 },
  { name: "Chuba Hubbard", realNflTeam: "CAR", position: "RB", externalId: "rb-hubbard", jerseyNumber: 30 },
  { name: "Kenneth Walker III", realNflTeam: "SEA", position: "RB", externalId: "rb-kwalker", jerseyNumber: 9 },
  { name: "Joe Mixon", realNflTeam: "HOU", position: "RB", externalId: "rb-mixon", jerseyNumber: 28 },
  { name: "David Montgomery", realNflTeam: "DET", position: "RB", externalId: "rb-montgomery", jerseyNumber: 5 },
  { name: "Rhamondre Stevenson", realNflTeam: "NE", position: "RB", externalId: "rb-stevenson", jerseyNumber: 38 },
  { name: "Tony Pollard", realNflTeam: "TEN", position: "RB", externalId: "rb-pollard", jerseyNumber: 20 },
  { name: "Aaron Jones", realNflTeam: "MIN", position: "RB", externalId: "rb-ajones", jerseyNumber: 33 },
  { name: "Najee Harris", realNflTeam: "PIT", position: "RB", externalId: "rb-harris", jerseyNumber: 22 },
  { name: "Isiah Pacheco", realNflTeam: "KC", position: "RB", externalId: "rb-pacheco", jerseyNumber: 10 },
  { name: "James Conner", realNflTeam: "ARI", position: "RB", externalId: "rb-conner", jerseyNumber: 6 },
  { name: "Rachaad White", realNflTeam: "TB", position: "RB", externalId: "rb-rwhite", jerseyNumber: 1 },
  { name: "Javonte Williams", realNflTeam: "DAL", position: "RB", externalId: "rb-jwilliams", jerseyNumber: 33 },
  { name: "Zack Moss", realNflTeam: "CIN", position: "RB", externalId: "rb-moss", jerseyNumber: 21 },
  { name: "Brian Robinson Jr.", realNflTeam: "WAS", position: "RB", externalId: "rb-brobinsonjr", jerseyNumber: 8 },
  { name: "Tyler Allgeier", realNflTeam: "ATL", position: "RB", externalId: "rb-allgeier", jerseyNumber: 25 },
  { name: "Austin Ekeler", realNflTeam: "WAS", position: "RB", externalId: "rb-ekeler", jerseyNumber: 30 },

  // Wide Receivers
  { name: "Ja'Marr Chase", realNflTeam: "CIN", position: "WR", externalId: "wr-chase", jerseyNumber: 1 },
  { name: "Justin Jefferson", realNflTeam: "MIN", position: "WR", externalId: "wr-jefferson", jerseyNumber: 18 },
  { name: "CeeDee Lamb", realNflTeam: "DAL", position: "WR", externalId: "wr-lamb", jerseyNumber: 88 },
  { name: "Amon-Ra St. Brown", realNflTeam: "DET", position: "WR", externalId: "wr-stbrown", jerseyNumber: 14 },
  { name: "Puka Nacua", realNflTeam: "LAR", position: "WR", externalId: "wr-nacua", jerseyNumber: 17 },
  { name: "Malik Nabers", realNflTeam: "NYG", position: "WR", externalId: "wr-nabers", jerseyNumber: 1 },
  { name: "Nico Collins", realNflTeam: "HOU", position: "WR", externalId: "wr-collins", jerseyNumber: 12 },
  { name: "A.J. Brown", realNflTeam: "PHI", position: "WR", externalId: "wr-ajbrown", jerseyNumber: 11 },
  { name: "Drake London", realNflTeam: "ATL", position: "WR", externalId: "wr-london", jerseyNumber: 5 },
  { name: "Brian Thomas Jr.", realNflTeam: "JAX", position: "WR", externalId: "wr-bthomas", jerseyNumber: 7 },
  { name: "Tyreek Hill", realNflTeam: "MIA", position: "WR", externalId: "wr-hill", jerseyNumber: 10 },
  { name: "Davante Adams", realNflTeam: "LAR", position: "WR", externalId: "wr-adams", jerseyNumber: 17 },
  { name: "Mike Evans", realNflTeam: "TB", position: "WR", externalId: "wr-evans", jerseyNumber: 13 },
  { name: "Chris Godwin", realNflTeam: "TB", position: "WR", externalId: "wr-godwin", jerseyNumber: 14 },
  { name: "DK Metcalf", realNflTeam: "PIT", position: "WR", externalId: "wr-metcalf", jerseyNumber: 4 },
  { name: "DJ Moore", realNflTeam: "CHI", position: "WR", externalId: "wr-djmoore", jerseyNumber: 2 },
  { name: "Terry McLaurin", realNflTeam: "WAS", position: "WR", externalId: "wr-mclaurin", jerseyNumber: 17 },
  { name: "Garrett Wilson", realNflTeam: "NYJ", position: "WR", externalId: "wr-gwilson", jerseyNumber: 17 },
  { name: "Jaxon Smith-Njigba", realNflTeam: "SEA", position: "WR", externalId: "wr-smithnjigba", jerseyNumber: 11 },
  { name: "Ladd McConkey", realNflTeam: "LAC", position: "WR", externalId: "wr-mcconkey", jerseyNumber: 15 },
  { name: "Rome Odunze", realNflTeam: "CHI", position: "WR", externalId: "wr-odunze", jerseyNumber: 15 },
  { name: "Zay Flowers", realNflTeam: "BAL", position: "WR", externalId: "wr-flowers", jerseyNumber: 4 },
  { name: "Jameson Williams", realNflTeam: "DET", position: "WR", externalId: "wr-jwilliams", jerseyNumber: 9 },
  { name: "Courtland Sutton", realNflTeam: "DEN", position: "WR", externalId: "wr-sutton", jerseyNumber: 14 },
  { name: "Jerry Jeudy", realNflTeam: "CLE", position: "WR", externalId: "wr-jeudy", jerseyNumber: 3 },
  { name: "Keenan Allen", realNflTeam: "LAC", position: "WR", externalId: "wr-kallen", jerseyNumber: 13 },
  { name: "Amari Cooper", realNflTeam: "BUF", position: "WR", externalId: "wr-cooper", jerseyNumber: 2 },
  { name: "Xavier Worthy", realNflTeam: "KC", position: "WR", externalId: "wr-worthy", jerseyNumber: 1 },
  { name: "Marvin Harrison Jr.", realNflTeam: "ARI", position: "WR", externalId: "wr-mharrison", jerseyNumber: 18 },
  { name: "Tank Dell", realNflTeam: "HOU", position: "WR", externalId: "wr-dell", jerseyNumber: 3 },
  { name: "Calvin Ridley", realNflTeam: "TEN", position: "WR", externalId: "wr-ridley", jerseyNumber: 0 },
  { name: "Diontae Johnson", realNflTeam: "BAL", position: "WR", externalId: "wr-djohnson", jerseyNumber: 18 },

  // Tight Ends
  { name: "Travis Kelce", realNflTeam: "KC", position: "TE", externalId: "te-kelce", jerseyNumber: 87 },
  { name: "Sam LaPorta", realNflTeam: "DET", position: "TE", externalId: "te-laporta", jerseyNumber: 87 },
  { name: "Trey McBride", realNflTeam: "ARI", position: "TE", externalId: "te-mcbride", jerseyNumber: 85 },
  { name: "George Kittle", realNflTeam: "SF", position: "TE", externalId: "te-kittle", jerseyNumber: 85 },
  { name: "Brock Bowers", realNflTeam: "LV", position: "TE", externalId: "te-bowers", jerseyNumber: 89 },
  { name: "Mark Andrews", realNflTeam: "BAL", position: "TE", externalId: "te-andrews", jerseyNumber: 89 },
  { name: "Evan Engram", realNflTeam: "DEN", position: "TE", externalId: "te-engram", jerseyNumber: 1 },
  { name: "Dallas Goedert", realNflTeam: "PHI", position: "TE", externalId: "te-goedert", jerseyNumber: 88 },
  { name: "David Njoku", realNflTeam: "CLE", position: "TE", externalId: "te-njoku", jerseyNumber: 85 },
  { name: "Jake Ferguson", realNflTeam: "DAL", position: "TE", externalId: "te-ferguson", jerseyNumber: 87 },
  { name: "Kyle Pitts", realNflTeam: "ATL", position: "TE", externalId: "te-pitts", jerseyNumber: 8 },
  { name: "Cole Kmet", realNflTeam: "CHI", position: "TE", externalId: "te-kmet", jerseyNumber: 85 },

  // Kickers
  { name: "Justin Tucker", realNflTeam: "BAL", position: "K", externalId: "k-tucker", jerseyNumber: 9 },
  { name: "Harrison Butker", realNflTeam: "KC", position: "K", externalId: "k-butker", jerseyNumber: 7 },
  { name: "Brandon Aubrey", realNflTeam: "DAL", position: "K", externalId: "k-aubrey", jerseyNumber: 17 },
  { name: "Jake Elliott", realNflTeam: "PHI", position: "K", externalId: "k-elliott", jerseyNumber: 4 },
  { name: "Chris Boswell", realNflTeam: "PIT", position: "K", externalId: "k-boswell", jerseyNumber: 9 },
  { name: "Tyler Bass", realNflTeam: "BUF", position: "K", externalId: "k-bass", jerseyNumber: 2 },
  { name: "Jason Sanders", realNflTeam: "MIA", position: "K", externalId: "k-sanders", jerseyNumber: 7 },
  { name: "Cameron Dicker", realNflTeam: "LAC", position: "K", externalId: "k-dicker", jerseyNumber: 12 },
  { name: "Younghoe Koo", realNflTeam: "ATL", position: "K", externalId: "k-koo", jerseyNumber: 6 },
  { name: "Ka'imi Fairbairn", realNflTeam: "HOU", position: "K", externalId: "k-fairbairn", jerseyNumber: 7 },

  // Defenses (team unit, one per real NFL franchise)
  { name: "Arizona Cardinals", realNflTeam: "ARI", position: "DEF", externalId: "def-ari" },
  { name: "Atlanta Falcons", realNflTeam: "ATL", position: "DEF", externalId: "def-atl" },
  { name: "Baltimore Ravens", realNflTeam: "BAL", position: "DEF", externalId: "def-bal" },
  { name: "Buffalo Bills", realNflTeam: "BUF", position: "DEF", externalId: "def-buf" },
  { name: "Carolina Panthers", realNflTeam: "CAR", position: "DEF", externalId: "def-car" },
  { name: "Chicago Bears", realNflTeam: "CHI", position: "DEF", externalId: "def-chi" },
  { name: "Cincinnati Bengals", realNflTeam: "CIN", position: "DEF", externalId: "def-cin" },
  { name: "Cleveland Browns", realNflTeam: "CLE", position: "DEF", externalId: "def-cle" },
  { name: "Dallas Cowboys", realNflTeam: "DAL", position: "DEF", externalId: "def-dal" },
  { name: "Denver Broncos", realNflTeam: "DEN", position: "DEF", externalId: "def-den" },
  { name: "Detroit Lions", realNflTeam: "DET", position: "DEF", externalId: "def-det" },
  { name: "Green Bay Packers", realNflTeam: "GB", position: "DEF", externalId: "def-gb" },
  { name: "Houston Texans", realNflTeam: "HOU", position: "DEF", externalId: "def-hou" },
  { name: "Indianapolis Colts", realNflTeam: "IND", position: "DEF", externalId: "def-ind" },
  { name: "Jacksonville Jaguars", realNflTeam: "JAX", position: "DEF", externalId: "def-jax" },
  { name: "Kansas City Chiefs", realNflTeam: "KC", position: "DEF", externalId: "def-kc" },
  { name: "Las Vegas Raiders", realNflTeam: "LV", position: "DEF", externalId: "def-lv" },
  { name: "Los Angeles Chargers", realNflTeam: "LAC", position: "DEF", externalId: "def-lac" },
  { name: "Los Angeles Rams", realNflTeam: "LAR", position: "DEF", externalId: "def-lar" },
  { name: "Miami Dolphins", realNflTeam: "MIA", position: "DEF", externalId: "def-mia" },
  { name: "Minnesota Vikings", realNflTeam: "MIN", position: "DEF", externalId: "def-min" },
  { name: "New England Patriots", realNflTeam: "NE", position: "DEF", externalId: "def-ne" },
  { name: "New Orleans Saints", realNflTeam: "NO", position: "DEF", externalId: "def-no" },
  { name: "New York Giants", realNflTeam: "NYG", position: "DEF", externalId: "def-nyg" },
  { name: "New York Jets", realNflTeam: "NYJ", position: "DEF", externalId: "def-nyj" },
  { name: "Philadelphia Eagles", realNflTeam: "PHI", position: "DEF", externalId: "def-phi" },
  { name: "Pittsburgh Steelers", realNflTeam: "PIT", position: "DEF", externalId: "def-pit" },
  { name: "San Francisco 49ers", realNflTeam: "SF", position: "DEF", externalId: "def-sf" },
  { name: "Seattle Seahawks", realNflTeam: "SEA", position: "DEF", externalId: "def-sea" },
  { name: "Tampa Bay Buccaneers", realNflTeam: "TB", position: "DEF", externalId: "def-tb" },
  { name: "Tennessee Titans", realNflTeam: "TEN", position: "DEF", externalId: "def-ten" },
  { name: "Washington Commanders", realNflTeam: "WAS", position: "DEF", externalId: "def-was" },
];
